params:
  num_of_items:
    - 1
    - 2
    - 5
  num_of_prices: 3
  num_of_other_features: 2
  depth_of_trees: 5
  base_price: 1000

option:
  solver: "cbc"
  TimeLimit: 30
  num_of_simulations: 1

model: "po_L"

algorithm:
  solver_naive: True
  solver_heuristic: True
  multi_start_local_search: True

solver_heuristic:
  NoRelHeurTime: 100
  MIPFocus: 1

multi_start_local_search:
  num_multi_start: 10
