breakfast:
  store_num: 2277
  category: "BAG SNACKS"
  sub_category: "PRETZELS"
  manufacturer: "SNYDER S"
  target_col: "UNITS"
  base_cols:
      - "YEAR"
      - "MONTH"
      - "DAY"
      - "PRICE"
      - "DESCRIPTION"
      - "UNITS"
  master_cols:
      - "YEAR"
      - "MONTH"
      - "DAY"
