solver_naive:
  solver: "gurobi"
  TimeLimit: 3600
solver_heuristics:
  solver: "gurobi"
  NoRelHeurTime: 100
  MIPFocus: 1
  TimeLimit: 300
multi_start_local_search:
  num_multi_start: 3
  seed: 0
milo_relax:
  solver: "gurobi"
  TimeLimit: 3600
  num_iteration: 10
coord_descent:
  num_iteration: 10
