model:
  # POORT_L:
  #   algorithm:
  #     - solver_naive
  #     # - solver_heuristics
  #     - multi_start_local_search
  #   prediction: ORT_L
  # POORT_L_alpha:
  #   algorithm:
  #     - solver_naive
  #     # - solver_heuristics
  #     # - multi_start_local_search
  #   prediction: ORT_L
  # POORT_LH:
  #   algorithm:
  #     - solver_naive
  #     # - solver_heuristics
  #     # - multi_start_local_search
  #   prediction: ORT_LH
  POLR:
    algorithm:
      - solver_naive
    prediction: linear_regression
