name: Run pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install poetry
        poetry install --no-dev
        poetry run pip install pytest flake8==4.0.1 black==22.1.0
    - name: Test with pytest
      run: make test
    - name: Check format
      run: make lint
